[US100202] add backend catalog
LittleLegend-Pengiun/ecommerce-k8s-app pull request #2
Opened 2023-11-30 10:40 UTC by duyphatbk

Add backend catalog

2023-11-30 13:44 UTC, LittleLegend-Pengiun requested changes

2023-11-30 13:44 UTC, LittleLegend-Pengiun commented on apps/backend/catalog-ms/src/main/resources/application.properties
> +server.port=8090
You should update the port in terraform as well.

2023-11-30 13:44 UTC, LittleLegend-Pengiun commented on apps/backend/catalog-ms/src/main/java/com/service/catalog/reposistory/CategoryReposistory.java
> +public interface CategoryReposistory extends JpaRepository<Category, String> {
why there are empty class here?

2023-11-30 17:02 UTC, duyphatbk commented on apps/backend/catalog-ms/src/main/resources/application.properties
> +server.port=8090
updated

2023-11-30 17:02 UTC, duyphatbk commented on apps/backend/catalog-ms/src/main/java/com/service/catalog/reposistory/CategoryReposistory.java
> +public interface CategoryReposistory extends JpaRepository<Category, String> {
It's standard

2023-12-01 11:52 UTC, LittleLegend-Pengiun submitted a review, later dismissed

2024-02-19 14:33 UTC, LittleLegend-Pengiun approved these changes

2024-02-19 14:33 UTC, merged