add catalog-fe with no vite...resetup all
LittleLegend-Pengiun/ecommerce-k8s-app pull request #3
Opened 2023-12-01 09:21 UTC by hieuhoang2901

2023-12-01 12:25 UTC, LittleLegend-Pengiun requested changes

2023-12-01 12:25 UTC, LittleLegend-Pengiun commented on apps/frontend/catalog-fe/Dockerfile
> -# Use an official Node runtime as a parent image
You should restore the Dockerfile and docker ignore

2023-12-22 13:40 UTC, LittleLegend-Pengiun submitted a review, later dismissed

2023-12-29 05:04 UTC, LittleLegend-Pengiun submitted a review, later dismissed

2024-01-03 14:30 UTC, duyphatbk approved these changes

2024-01-03 14:31 UTC, LittleLegend-Pengiun approved these changes

2024-01-03 14:32 UTC, merged